id: au.edu.adelaide.rbrc.skinscreening
canonical: https://susith-athukorala.github.io/skin-screening-ig
name: RBRCSkinScreeningIG
title: "Skin Screening FHIR Implementation Guide"
description: "FHIR R4 Implementation Guide for Skin Screening, Teledermatology, and Lesion Monitoring."
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026
releaseLabel: ci-build
license: CC0-1.0

publisher:
  name: "Rosemary Bryant AO Research Centre, Adelaide University, Australia"
  url: "https://adelaide.edu.au/research/rosemary-bryant-ao-research-centre/"

jurisdiction: urn:iso:std:iso:3166#AU "Australia"

pages:
  index.md:
    title: Home
  background.md:
    title: Clinical Background & Workflow
  conformance.md:
    title: Must Support & Conformance
  security.md:
    title: Security & Privacy

menu:
  Home: index.html
  Guidance:
    Clinical Background & Workflow: background.html
    Must Support & Conformance: conformance.html
    Security & Privacy: security.html
  FHIR Artifacts:
    Profiles: artifacts.html#structures-resource-profiles
    Terminology: artifacts.html#terminology-value-sets
    Examples: artifacts.html#example-example-instances
  Artifact Index: artifacts.html
  Support:
    Downloads: downloads.html
    QA Report: qa.html

parameters:
  show-inherited-invariants: false
